# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build Windows x64

on:
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        default: false
      branch:
        type: string
        required: true
      ref:
        type: string
        required: true

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    name: Windows 2022 x64
    runs-on: windows-2022
    env:
      # macOS codesigning (unused, kept for parity)
      MACOS_CODESIGN_CERTIFICATE_P12_BASE64: ""
      MACOS_CODESIGN_CERTIFICATE_PASSWORD: ""
    outputs:
      artifact-windows-win64: ${{ steps.prepare_deploy.outputs.artifact-windows-win64 }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Ensure that all tags are fetched"
        run: git fetch origin --force --tags

      - name: "[Windows] Set up cmake"
        uses: jwlawson/actions-setup-cmake@v2.2
        with:
          cmake-version: "3.30.x"

      - name: "[Windows] Set up MSVC Developer Command Prompt"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: "[Windows] Set up build environment"
        shell: cmd
        run: tools/windows_buildenv.bat setup
        env:
          BUILDENV_BASEPATH: C:\buildenv
          BUILDENV_RELEASE: TRUE

      - name: "Create build directory"
        run: mkdir build

      - name: "Configure"
        run: >-
          cmake
          -DBULK=ON
          -DHSS1394=ON
          -DLOCALECOMPARE=ON
          -DMAD=ON
          -DMEDIAFOUNDATION=ON
          -DMODPLUG=ON
          -DQT6=ON
          -DQML=ON
          -DWAVPACK=ON
          -DVCPKG_TARGET_TRIPLET=x64-windows-release
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}"
          -DWARNINGS_FATAL=ON
          -DDEBUG_ASSERTIONS_FATAL=OFF
          -DBATTERY=ON
          -DBROADCAST=ON
          -DDOWNLOAD_MANUAL=ON
          -DHID=ON
          -DKEYFINDER=ON
          -DLILV=ON
          -DOPUS=ON
          -DQTKEYCHAIN=ON
          -DVINYLCONTROL=ON
          -DCMAKE_VERBOSE_MAKEFILE=OFF
          -L
          ..
        working-directory: build
        env:
          CC: cl
          CXX: cl

      - name: "[Windows] Set up MSVC problem matcher"
        uses: ammaraskar/msvc-problem-matcher@0.3.0

      - name: "Build"
        run: cmake --build . --config RelWithDebInfo
        working-directory: build
        env:
          CC: cl
          CXX: cl

      - name: "Test"
        run: ctest --timeout 45 --exclude-regex '^AutoDJProcessorTest.*$'
        working-directory: build
        env:
          GTEST_COLOR: 1
          CTEST_PARALLEL_LEVEL: 1
          CTEST_OUTPUT_ON_FAILURE: 1

      - name: "[Windows] Sign executables"
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        if: env.AZURE_TENANT_ID != ''
        uses: azure/trusted-signing-action@v1.1.0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://weu.codesigning.azure.net/
          trusted-signing-account-name: mixxx
          certificate-profile-name: mixxx
          files-folder: build
          files-folder-filter: exe
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          timeout: 600

      - name: "[Windows] Sign WiX custom action DLL"
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        if: env.AZURE_TENANT_ID != ''
        uses: azure/trusted-signing-action@v1.1.0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://weu.codesigning.azure.net/
          trusted-signing-account-name: mixxx
          certificate-profile-name: mixxx
          files: ${{ github.workspace }}/build/packaging/wix/mixxxupgradecustomaction.dll
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          timeout: 600

      - name: "[Windows] Install WiX Toolset"
        shell: pwsh
        run: |
          dotnet.exe tool install --global wix --version 6.0.2
          wix extension add --global WixToolset.UI.wixext/6.0.2

      - name: "Package"
        id: package
        run: cpack -G WIX -V
        working-directory: build

      - name: "Upload failed packaging logs"
        if: always() && steps.package.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: windows-2022-logs-packages-wix
          path: ${{ github.workspace }}/build/_CPack_Packages/win64/WIX/wix.log

      - name: "[Windows] Sign installer"
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        if: env.AZURE_TENANT_ID != ''
        uses: azure/trusted-signing-action@v1.1.0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://weu.codesigning.azure.net/
          trusted-signing-account-name: mixxx
          certificate-profile-name: mixxx
          files-folder: build
          files-folder-filter: msi
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          timeout: 600

      - name: "Prepare for deployment"
        id: prepare_deploy
        if: inputs.publish
        shell: bash
        run: >
          if [[ "${{ inputs.ref }}" =~ ^refs/tags/.* ]];
          then
            export DEPLOY_PATH='releases/{git_describe}/mixxx-{git_describe}-{package_slug}{ext}';
          else
            export DEPLOY_PATH='snapshots/{git_branch}/mixxx-{git_describe}-{package_slug}{ext}';
          fi;
          python3 tools/deploy.py prepare-deployment
          --slug 'windows-win64'
          --output-dir 'deploy/'
          --dest-path "${DEPLOY_PATH}"
          --dest-url 'https://downloads.mixxx.org'
          build/*.msi

      - name: "[Windows] Install rsync and openssh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DOWNLOADS_HOSTGATOR_DOT_MIXXX_DOT_ORG_KEY }}
        if: inputs.publish && env.SSH_PRIVATE_KEY != ''
        run: |
          if (Test-Path "C:\msys64\usr\bin") {
            $msysPath="C:\msys64"
          } else {
            choco install msys2 -y
            $msysPath="C:\tools\msys64"
          }
          $Env:PATH="$msysPath\usr\bin;$Env:PATH"
          pacman -S --noconfirm coreutils bash rsync openssh
          Copy-Item -Path "$msysPath\usr\bin\bash.exe" -Destination "C:\Program Files\Git\bin\bash.exe" -Force
          Remove-Item -Path "$msysPath\etc\profile"
          Add-Content -Path "$Env:GITHUB_ENV" -Value "PATH=$Env:PATH"

      - name: "Set up SSH Agent"
        if: inputs.publish && env.SSH_PRIVATE_KEY != ''
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.DOWNLOADS_HOSTGATOR_DOT_MIXXX_DOT_ORG_KEY }}
          SSH_HOST: downloads-hostgator.mixxx.org
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          mkdir -p "${HOME}/.ssh"
          ssh-keyscan "${SSH_HOST}" >> "${HOME}/.ssh/known_hosts"
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "${GITHUB_ENV}"

      - name: "Upload build to downloads.mixxx.org"
        if: inputs.publish && env.SSH_AUTH_SOCK != ''
        shell: bash --login -eo pipefail "{0}"
        run: rsync --verbose --recursive --checksum --times --delay-updates "deploy/" "${SSH_USER}@${SSH_HOST}:${DESTDIR}/"
        env:
          DESTDIR: public_html/downloads
          SSH_HOST: downloads-hostgator.mixxx.org
          SSH_USER: mixxx

      - name: "Use system tar & zstd from Chocolatey for caching"
        shell: bash
        run: |
          echo "C:/Windows/System32;C:/ProgramData/Chocolatey/bin" >> $GITHUB_PATH

      - name: "Upload GitHub Actions artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: Windows x64 Installer
          path: build/*.msi
